# Generated by Django 3.1.4 on 2021-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('filetype', models.FileField(upload_to='songs/filetype/')),
            ],
        ),
    ]
