# Generated by Django 3.1.4 on 2021-02-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_songfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlee', models.CharField(max_length=100)),
                ('filetypee', models.FileField(upload_to='songs/filetype/')),
                ('duration', models.CharField(max_length=10)),
                ('samp_freq', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
