# Generated by Django 3.1.4 on 2021-02-18 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_songdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongData',
        ),
        migrations.AddField(
            model_name='songfile',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songfile',
            name='samp_freq',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
