# Generated by Django 3.1.4 on 2021-02-18 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20210218_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
