# Generated by Django 3.1.4 on 2021-02-19 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_songfile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='audioimage'),
            preserve_default=False,
        ),
    ]
