# Generated by Django 3.1.4 on 2021-02-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20210219_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songfile',
            old_name='filetype',
            new_name='audio',
        ),
    ]
